### ISSUE TITLE
What should we use for Solar metallicity?

### ISSUE THREAD

**Issue by michaelzevin** [COSMIC-PopSynth/COSMIC#346]
In most other popsynth codes I've seen, they are using more up-to-date values of Zsun. For example, COMPAS uses 0.0142 from https://ui.adsabs.harvard.edu/abs/2009ARA%26A..47..481A/abstract (rather than 0.02, which we use). 

This will actually have a non-negligible effect on MW populations. 

Thoughts on this @katiebreivik @scottcoughlin2014?

**Comment by katiebreivik** [comment]
I think this is closely tied to this issue: https://github.com/COSMIC-PopSynth/COSMIC/issues/344

Since we are going to remove model-dependent choices for the thin/thick disk and bulge star formation histories, I think it's also a good idea to remove model dependent choices for metallicity. One way to go about this is to explicitly state what the star formation history and metallicity choices are in each paper we write, and maybe link to the papers in the documentation? We could also link to other choices (e.g. COMPAS?) too. My reasoning is that COSMIC is pretty functional already when it comes to setting metallicity, so it's better to keep it the way it is and allow updates which we trace through papers rather than having a metallicity endorsed by the COSMIC developers.

Once I get my act together for the PR that solves #344, this one could probably be solved with it as well.

Thoughts?

**Comment by michaelzevin** [comment]
I think that sounds good, though we still need a default for the Params.ini file. 

I personally think good defaults will be "Delta Burst", with an up-to-date estimate of Solar metallicity (0.014)

**Comment by katiebreivik** [comment]
I agree that the delta burst is a good way to go (I think this is already the case in the Params.ini file), but I'm not sure about changing the defaults to solar metallicity being 0.014 quite yet, since we would need to re-run the models for the paper again. Maybe we chat in person next week?

**Comment by scottcoughlin2014** [comment]
#368 is the real issue

**Comment by michaelzevin** [comment]
Looks like we've converged on Grevesse & Sauval 1998 for Zsun (0.017)

**Comment by scottcoughlin2014** [comment]
link the PR and closed
