### ISSUE TITLE
Non consistent fallback fraction for delayed core-collapse prescription 

### ISSUE THREAD

**Issue by JRGarza** [COSMIC-PopSynth/COSMIC#432]
At line 635 on the hrdiag.f module, the delayed core-collapse prescription, i.e. `remnantflag = 4`, rewrites the fallback fraction to a zero value, as `fallback = 0.d0`. This seems to not be consistent with Fryer+12, i.e. `fallback = 0.2d0 / (mt - mcx)`. As there is no other reference on that part of the code I wonder if this is a mistake.

https://github.com/COSMIC-PopSynth/COSMIC/blob/ca1b352ab9d062c851301bb98f2f8c587e5841c4/cosmic/src/hrdiag.f#L635

@michaelzevin @ssbvr

**Comment by michaelzevin** [comment]
Hmmm...it looks like this is the case also at L1009. Both instances shouldn't affect anything, though, since `mt` is calculated correctly. 

I wonder if this change was made due to an update to Fryer's delayed prescription. @carlrodriguez you don't have any reason to think this would be the case, do you?

**Comment by michaelzevin** [comment]
This is fixed in #537. We did digging and couldn't find the reasoning for why `fallback = 0.d0` was set, so reverted to what is done in Fryer+2012 exactly.
