### ISSUE TITLE
Create a separate fortran module

### ISSUE THREAD

**Issue by astroJeff** [COSMIC-PopSynth/COSMIC#68]
We discussed at the meeting this week about spinning off the fortran code and executable into its own repository which can then be loaded into the cosmic population synthesis wrapper.

**Comment by astroJeff** [comment]
I vote for a separate repository with the python wrapper. It would make it easier for importing into external projects, and we can separately/independently make updates to the binary evolution physics. If we go this route, we'll need to think a bit about the API.

**Comment by scottcoughlin2014** [comment]
Hey @astroJeff, @katiebreivik and I were discussing this exact point and Katie gave me a convincing reason to leave it at the separate repo for the fortran code. However, we have it on the agenda for discussion and we are open to being convinced otherwise. I will let Katie reiterate her point on the call.

**Comment by scottcoughlin2014** [comment]
I think we are not going to do this anymore
