### ISSUE TITLE
Changes to "formation_1/2" series

### ISSUE THREAD

**Issue by michaelzevin** [COSMIC-PopSynth/COSMIC#86]
Change the "formation_1" and "formation_2" series to "SN1" and "SN2". 

Default should be set to 0. 

Also, need to determine what the current ints represent in these series.

**Comment by scottcoughlin2014** [comment]
@michaelzevin @katiebreivik before I can do a full unit tests upgrade (i.e. including more init conditions that lead to things like NSBH BBH BNS and other systems that we want BSE to produce so we can see if future changes to the fortran code breaks the creation of such systems) I would like to finalize the headers of our `bpp` `bcm` arrays (this seems to be the last major change as we now have `merger_type` and `bin_state` in the bcm. So is this entire PR just changing the name of the column? or anything deeper? Because that can happen quickly.
